name: Unity Multiplatform Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64
          - StandaloneOSX
          - StandaloneLinux64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Unity - Activate license
        uses: game-ci/unity-activate@v2
        with:
          unityVersion: 6000.0.29f1
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

      - name: Unity - Build ${{ matrix.targetPlatform }}
        uses: game-ci/unity-builder@v2
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          unityVersion: 6000.0.29f1

      - name: Archive build
        run: |
          zip -r Build-${{ matrix.targetPlatform }}.zip build/${{ matrix.targetPlatform }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: Build-${{ matrix.targetPlatform }}.zip
